#pragma once
//-------------------------------------------------------------------------------
// -> platform
//      KUN_PLAT_WIN32
//      KUN_PLAT_WIN64
//
// -> architecture
//      KUN_ARCH_X86
//      KUN_ARCH_X86_64
//
//-------------------------------------------------------------------------------

// platform
#ifndef KUN_PLATFORM_WIN32
    #define KUN_PLATFORM_WIN32 0
#endif
#ifndef KUN_PLATFORM_WIN64
    #define KUN_PLATFORM_WIN64 0
#endif

// architecture
#ifndef KUN_ARCH_X86
    #define KUN_ARCH_X86 0
#endif
#ifndef KUN_ARCH_X86_64
    #define KUN_ARCH_X86_64 0
#endif